# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: "Install SSH Key"
description: "Install SSH key in ~/.ssh"
author: "shimataro"
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  key:
    description: "SSH private key"
    required: true
  name:
    description: "SSH key file name (default: id_rsa)"
    required: false
    default: "id_rsa"
  known_hosts:
    description: "public keys of SSH servers"
    required: false
    default: |
      # github.com:22 SSH-2.0-babeld-f1c576c9
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      # github.com:22 SSH-2.0-babeld-f1c576c9
      github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      # github.com:22 SSH-2.0-babeld-f1c576c9
      # github.com:22 SSH-2.0-babeld-f1c576c9
      github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
      # github.com:22 SSH-2.0-babeld-f1c576c9
  config:
    description: "SSH config"
    required: false
    default: ""
  if_key_exists:
    description: "replace / ignore / fail"
    required: false
    default: "fail"
runs:
  using: "node16"
  main: "lib/index.js"
  post: "lib/index.js"
